"""SQLAlchemy 2.0 async ORM models.

Works with both SQLite (aiosqlite) and PostgreSQL (asyncpg).
The engine is selected at runtime from config.yaml or DATABASE_URL env var.
"""

from __future__ import annotations

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
    select,
)
from sqlalchemy.orm import DeclarativeBase, relationship


class Base(DeclarativeBase):
    pass


class Asset(Base):
    """Configured trading assets."""

    __tablename__ = "assets"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, unique=True, index=True)
    display_name = Column(String(100), nullable=False, default="")
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class Signal(Base):
    """Signals generated by the system when entry conditions align."""

    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime(timezone=True), nullable=False)
    symbol = Column(String(20), nullable=False, index=True)
    direction = Column(String(10), nullable=False)
    entry_price = Column(Float, nullable=False)
    stop_loss = Column(Float, nullable=False)
    take_profit = Column(Float, nullable=False)
    quality_score = Column(Integer, default=0)
    mtf_alignment = Column(String(20))
    regime = Column(String(10))
    sentiment_score = Column(Float)
    composite_score = Column(String(10))
    confidence_pct = Column(Float)
    session = Column(String(20))
    outcome = Column(String(20), default="PENDING")
    outcome_price = Column(Float)
    outcome_pips = Column(Float)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    trades = relationship("Trade", back_populates="signal")

    __table_args__ = (Index("ix_signals_symbol_ts", "symbol", "timestamp"),)


class Trade(Base):
    """Trades recorded manually by the trader."""

    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_id = Column(Integer, ForeignKey("signals.id"), nullable=True)
    timestamp = Column(DateTime(timezone=True), nullable=False)
    symbol = Column(String(20), nullable=False, index=True)
    direction = Column(String(10), nullable=False)
    entry_price = Column(Float, nullable=False)
    exit_price = Column(Float)
    stop_loss = Column(Float)
    take_profit = Column(Float)
    quality_score = Column(Integer, default=0)
    regime = Column(String(10))
    sentiment_score = Column(Float)
    outcome_pips = Column(Float, default=0)
    r_multiple = Column(Float, default=0)
    notes = Column(Text)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    signal = relationship("Signal", back_populates="trades")


class MonitorSession(Base):
    """Active monitoring sessions for assets."""

    __tablename__ = "monitor_sessions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, unique=True)
    interval_seconds = Column(Integer, default=60)
    started_at = Column(DateTime(timezone=True), server_default=func.now())
    last_check = Column(DateTime(timezone=True))
    status = Column(String(10), default="ACTIVE")
    last_price = Column(Float)
    last_signal = Column(Text)


class NotificationLog(Base):
    """Log of sent notifications (for rate limiting and debugging)."""

    __tablename__ = "notification_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime(timezone=True), server_default=func.now())
    type = Column(String(20), nullable=False)
    symbol = Column(String(20))
    message = Column(Text)
    channel = Column(String(20), nullable=False)


class AnalysisCache(Base):
    """Cache for analysis results to avoid re-fetching."""

    __tablename__ = "analysis_cache"

    symbol = Column(String(20), primary_key=True)
    data_type = Column(String(20), primary_key=True)
    data_json = Column(Text, nullable=False)
    expires_at = Column(DateTime(timezone=True), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now())


class RssFeed(Base):
    """RSS news feed sources for sentiment analysis."""

    __tablename__ = "rss_feeds"

    id = Column(Integer, primary_key=True, autoincrement=True)
    url = Column(String(500), nullable=False, unique=True)
    name = Column(String(100), nullable=False, default="")
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class TelegramConfig(Base):
    """Telegram notification settings (runtime-mutable via Settings UI).

    Singleton row (id=1). Values here override environment variable defaults.
    """

    __tablename__ = "telegram_config"

    id = Column(Integer, primary_key=True, default=1)
    bot_token = Column(String(200), nullable=False, default="")
    chat_id = Column(String(50), nullable=False, default="")
    enabled = Column(Boolean, nullable=False, default=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now())


# ---------------------------------------------------------------------------
# Asset helpers
# ---------------------------------------------------------------------------


async def seed_assets_from_config(session_factory, config: dict) -> None:
    """Seed assets table from config.yaml if the table is empty."""
    async with session_factory() as session:
        count = await session.scalar(select(func.count()).select_from(Asset))
        if count and count > 0:
            return

        for item in config.get("assets", []):
            session.add(
                Asset(
                    symbol=item["symbol"],
                    display_name=item.get("display_name", item["symbol"]),
                )
            )
        await session.commit()


async def get_all_assets(session_factory) -> list[dict]:
    """Return all assets as list of dicts (same shape as config.yaml)."""
    async with session_factory() as session:
        result = await session.execute(select(Asset).order_by(Asset.symbol))
        rows = result.scalars().all()
    return [{"symbol": r.symbol, "display_name": r.display_name} for r in rows]


# ---------------------------------------------------------------------------
# RSS feed helpers
# ---------------------------------------------------------------------------

DEFAULT_RSS_FEEDS = [
    {
        "url": "https://feeds.finance.yahoo.com/rss/2.0/headline?s=^IXIC&region=US&lang=en-US",
        "name": "Yahoo Finance NASDAQ",
    },
    {
        "url": "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114",
        "name": "CNBC Top News",
    },
    {
        "url": "https://www.investing.com/rss/news_14.rss",
        "name": "Investing.com",
    },
    {
        "url": "https://feeds.marketwatch.com/marketwatch/topstories/",
        "name": "MarketWatch Top Stories",
    },
]


async def seed_rss_feeds(session_factory, feeds: list[dict] | None = None) -> None:
    """Seed RSS feeds table if empty. Uses provided feeds or defaults."""
    async with session_factory() as session:
        count = await session.scalar(select(func.count()).select_from(RssFeed))
        if count and count > 0:
            return

        for item in feeds or DEFAULT_RSS_FEEDS:
            session.add(RssFeed(url=item["url"], name=item.get("name", item["url"])))
        await session.commit()


async def get_all_rss_feeds(session_factory) -> list[dict]:
    """Return all RSS feeds as list of dicts."""
    async with session_factory() as session:
        result = await session.execute(select(RssFeed).order_by(RssFeed.id))
        rows = result.scalars().all()
    return [{"url": r.url, "name": r.name} for r in rows]


# ---------------------------------------------------------------------------
# Telegram config helpers
# ---------------------------------------------------------------------------


async def get_telegram_config(session_factory) -> dict:
    """Return telegram config from DB, or empty defaults if not set."""
    async with session_factory() as session:
        row = await session.get(TelegramConfig, 1)
    if row:
        return {
            "bot_token": row.bot_token,
            "chat_id": row.chat_id,
            "enabled": row.enabled,
        }
    return {"bot_token": "", "chat_id": "", "enabled": False}


async def upsert_telegram_config(
    session_factory, bot_token: str, chat_id: str, enabled: bool
) -> None:
    """Insert or update the singleton telegram config row."""
    async with session_factory() as session:
        row = await session.get(TelegramConfig, 1)
        if row:
            row.bot_token = bot_token
            row.chat_id = chat_id
            row.enabled = enabled
        else:
            session.add(
                TelegramConfig(
                    id=1,
                    bot_token=bot_token,
                    chat_id=chat_id,
                    enabled=enabled,
                )
            )
        await session.commit()
